restaurants = {
    'name': "Santos Manjares",
    'type': 'restaurant',
    'budget': 'cheap',
    'distance': 'walking',
    'meal_type': ['lunch', 'dinner'],
    'cuisine': 'argentinian',
    'vibe': 'casual',
    'reservation': 'no',
    'group_size': ['solo','couple','small_group', 'large_group'],
    'wifi': 'no',
    'address': 'Paraguay 938, C1057AAL Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Santos+Manjares'
},
{
    'name': "Surrey Hills Arevalo",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'short_ride',
    'meal_type': ['brunch', 'lunch'],
    'cuisine': 'australian',
    'vibe': 'chill',
    'reservation': 'yes',
    'group_size': ['solo','couple','small_group'],
    'wifi': 'yes',
    'address': 'Arévalo 1564, C1414 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Surrey+Hills+Arevalo'
},
{
    'name': "Empanadas del Mundo",
    'type': 'restaurant',
    'budget': 'cheap',
    'distance': 'walking',
    'meal_type': ['lunch', 'dinner'],
    'cuisine': 'international',
    'vibe': 'casual',
    'reservation': 'no',
    'group_size': ['solo'],
    'wifi': 'no',
    'address': 'Av. Santa Fe 849, C1059ABC Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Empanadas+del+Mundo'
},
{
    'name': "Parrilla Cero5",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'walking',
    'meal_type': 'dinner',
    'cuisine': 'argentinian',
    'vibe': 'lively',
    'reservation': 'yes',
    'group_size': ['couple','small_group','large_group'],
    'wifi': 'no',
    'address': 'Av. Corrientes 325, C1043AAD Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Parrilla+Cero5'
},
{
    'name': "La Cocina de Amira",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'walking',
    'meal_type': ['lunch', 'dinner'],
    'cuisine': 'halal',
    'vibe': 'casual',
    'reservation': 'no',
    'group_size': ['solo','couple','small_group'],
    'wifi': 'no',
    'address': 'Montevideo 559, C1019 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/La+Cocina+de+Amira'
},
{
    'name': "Sarkis",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'short_ride',
    'meal_type': ['lunch', 'dinner'],
    'cuisine': 'armenian',
    'vibe': 'busy',
    'reservation': 'no',
    'group_size': ['couple','small_group'],
    'wifi': 'no',
    'address': 'Thames 1101, C1414 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Sarkis'
},
{
    'name': "Il Vero Arturito",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'short_ride',
    'meal_type': 'dinner',
    'cuisine': 'italian',
    'vibe': 'cozy',
    'reservation': 'yes',
    'group_size': ['couple','small_group'],
    'wifi': 'yes',
    'address': 'Arturo Illia 418, C1005 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Il+Vero+Arturito'
},
{
    'name': "Gordo Vegano",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'long_ride',
    'meal_type': ['lunch', 'dinner'],
    'cuisine': 'vegan',
    'vibe': 'casual',
    'reservation': 'no',
    'group_size': ['solo','couple','small_group'],
    'wifi': 'no',
    'address': 'Echeverría 3078, C1428 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Gordo+Vegano'
},
{
    'name': "Sampa",
    'type': 'restaurant',
    'budget': 'expensive',
    'distance': 'short_ride',
    'meal_type': 'dinner',
    'cuisine': 'vegetarian',
    'vibe': 'upscale',
    'reservation': 'yes',
    'group_size': ['couple','small_group'],
    'wifi': 'yes',
    'address': 'Scalabrini Ortiz 769, C1414 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Sampa+Buenos+Aires'
},
{
    'name': "Tanta Argentina",
    'type': 'restaurant',
    'budget': 'moderate',
    'distance': 'walking',
    'meal_type': ['lunch', 'dinner'],
    'cuisine': 'peruvian',
    'vibe': 'lively',
    'reservation': 'yes',
    'group_size': ['solo','couple','small_group','large_group'],
    'wifi': 'yes',
    'address': 'Esmeralda 938, C1007 Cdad. Autónoma de Buenos Aires',
    'google_maps': 'https://www.google.com/maps/place/Tanta+Argentina'
}